<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Chameleon.lib.Common</RootNamespace>
		<AssemblyTitle>Chameleon.lib.Common</AssemblyTitle>
		<Description>Chameleon.lib.Common for chameleonmode</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageId>Chameleon.lib.Common$(PackageSuffix)</PackageId>
		<Configurations>Debug;Release</Configurations>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Management" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Chameleon.lib\Chameleon.lib.csproj" />
	</ItemGroup>

</Project>
