<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Chameleon.lib.Core</RootNamespace>
		<AssemblyTitle>Chameleon.lib.Core</AssemblyTitle>
		<Description>Chameleon.lib.Core for chameleonmode</Description>
		<Configuration></Configuration>
		<Company></Company>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageId>Chameleon.lib.Core$(PackageSuffix)</PackageId>
		<Configurations>Debug;Release</Configurations>
		<OutputPath>$(MSBuildProjectDirectory)\bin\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
	</ItemGroup>

</Project>
