export const config = {
    enabled: true,
    debug: 5,
    webglSpoofing: true,
    canvasProtection: true,
    clientRectsSpoofing: true,
    fontsSpoofing: true,
    audioSpoofing: true,
    geoSpoofing: true,
    timezoneSpoofing: true,
    timezone: "Asia/Jerusalem",
    latitude: 31.7674,
    longitude: 35.2186,
    myIP: false,
    dAPI: true,
    webRtcEnabled: true,
    randomizeTZ: false,
    randomizeGeo: false,
    noiseLevel: "medium",
    eMode: "disable_non_proxied_udp",
    dMode: "default_public_interface_only",
    locale: "en-US",
    accuracy: 69.96,
    bypass: [],
    history: []
  };