<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Chameleon.lib.CommunityToolkit</RootNamespace>
		<AssemblyTitle>Chameleon.lib.CommunityToolkit</AssemblyTitle>
		<Description>Chameleon.lib.CommunityToolkit for chameleonmode</Description>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<PackageId>Chameleon.lib.CommunityToolkit$(PackageSuffix)</PackageId>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.HighPerformance" />
	  <PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
	</ItemGroup>

</Project>
