<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<RootNamespace>Chameleon.lib.CommunityToolkit</RootNamespace>
		<AssemblyTitle>Chameleon.lib.CommunityToolkit</AssemblyTitle>
		<Description>Chameleon.lib.CommunityToolkit for chameleonmode</Description>
		<Configuration></Configuration>
		<Company></Company>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageId>Chameleon.lib.CommunityToolkit$(PackageSuffix)</PackageId>
		<Configurations>Debug;Release</Configurations>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="CommunityToolkit.HighPerformance" />
	  <PackageReference Include="CommunityToolkit.Mvvm" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Chameleon\src\Chameleon.Interfaces\Chameleon.Interfaces.csproj" />
	</ItemGroup>

</Project>
