<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Chameleon.Assets/chameleon.assets.csproj" />
    <ProjectReference Include="..\Chameleon.lib\Chameleon.lib.csproj" />
    <!-- ASP.NET Core references -->
    <!-- Use the Microsoft.AspNetCore.App metapackage for .NET 8 -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
