namespace Chameleon.lib.Common.Models;
public class SysBrowserPreferences {
	public string compact_mode { get; set; }
	public string default_apps { get; set; }
	public string safebrowsing_for_trusted_sources_enabled { get; set; }
	public string disable_screenshots { get; set; }
	public string download_restrictions { get; set; }
	public Download_Bubble download_bubble { get; set; }
	public Profile profile { get; set; }
	public string homepage_is_newtabpage { get; set; }
	public string homepage { get; set; }
	public string https_only_mode_enabled { get; set; }
	public string https_first_balanced_mode_enabled { get; set; }
	public string https_first_mode_incognito_enabled { get; set; }
	public string https_only_mode_auto_enabled { get; set; }
	public string https_upgrade_fallbacks { get; set; }
	public string https_upgrade_navigations { get; set; }
	public string important_sites_dialog { get; set; }
	public string newtab_page_location_override { get; set; }
	public Session session { get; set; }
	public string feedback_allowed { get; set; }
	public Intl intl { get; set; }
	public Webkit webkit { get; set; }
	public string Zyyy { get; set; }
	public Ssl ssl { get; set; }
	public Search search { get; set; }
	public Download download { get; set; }
	public Net net { get; set; }
	public string default_apps_install_state { get; set; }
	public Browser browser { get; set; }
	public Settings settings { get; set; }
	public Extensions1 extensions { get; set; } = new();
	public Autogenerated autogenerated { get; set; }
	public string syncing_theme_prefs_migrated_to_non_syncing { get; set; }
	public string should_read_incoming_syncing_theme_prefs { get; set; }
	public Plugins plugins { get; set; }
	public Accessibility accessibility { get; set; }
	public Partition partition { get; set; }
	public string pinned_tabs { get; set; }
	public string disable_3d_apis { get; set; }
	public string enable_a_ping { get; set; }
	public string enable_referrers { get; set; }
	public Media media { get; set; }
	public string import_autofill_form_data { get; set; }
	public string import_bookmarks { get; set; }
	public string import_history { get; set; }
	public string import_home_page { get; set; }
	public string import_saved_passwords { get; set; }
	public string import_search_engine { get; set; }
	public string import_dialog_autofill_form_data { get; set; }
	public string import_dialog_bookmarks { get; set; }
	public string import_dialog_history { get; set; }
	public string import_dialog_saved_passwords { get; set; }
	public string import_dialog_search_engine { get; set; }
	public string invert_notification_version_2_shown { get; set; }
	public Printing printing { get; set; }
	public Downgrade downgrade { get; set; }
	public Message_Center message_center { get; set; }
	public Fullscreen fullscreen { get; set; }
	public Gcm gcm { get; set; }
	public Easy_Unlock easy_unlock { get; set; }
	public Webrtc webrtc { get; set; }
	public string suppress_different_origin_subframe_js_dialogs { get; set; }
	public string user_agent_reduction { get; set; }
	public Side_Panel side_panel { get; set; }
	public Tab_Search tab_search { get; set; }
	public string managed_private_network_access_restrictions_enabled { get; set; }
	public string chrome_data_region_setting { get; set; }
	public string network_annotation_blocklist { get; set; }
	public Enterprise_Reporting enterprise_reporting { get; set; }
	public Managed managed { get; set; }
	public Profiles profiles { get; set; }
	public User_Experience_Metrics user_experience_metrics { get; set; }
	public Task_Manager task_manager { get; set; }
	public Savefile savefile { get; set; }
	public Selectfile selectfile { get; set; }
	public Select_File_Dialogs select_file_dialogs { get; set; }
	public Filebrowser filebrowser { get; set; }
	public Protocol_Handler protocol_handler { get; set; }
	public Restart restart { get; set; }
	public Was was { get; set; }
	public Ntp ntp { get; set; }
	public Newtabpage NewTabPage { get; set; }
	public Colorpicker colorpicker { get; set; }
	public Devtools devtools { get; set; }
	public Sync_Promo sync_promo { get; set; }
	public Web_App2 web_app { get; set; }
	public string web_app_install_metrics { get; set; }
	public Web_Apps web_apps { get; set; }
	public Background_Contents background_contents { get; set; }
	public string total_memory_limit_mb { get; set; }
	public Auth auth { get; set; }
	public Hsts hsts { get; set; }
	public Async_Dns async_dns { get; set; }
	public Dns_Over_Https dns_over_https { get; set; }
	public Hardware hardware { get; set; }
	public Feedback feedback { get; set; }
	public string FactoryResetRequested { get; set; }
	public string ForceFactoryReset { get; set; }
	public string FactoryResetTPMFirmwareUpdateMode { get; set; }
	public string DebuggingFeaturesRequested { get; set; }
	public string EnableAdbSideloadingRequested { get; set; }
	public Media_Router media_router { get; set; }
	public string qr_code_generator_enabled { get; set; }
	public Cloud_Print cloud_print { get; set; }
	public Background_Mode background_mode { get; set; }
	public Hardware_Acceleration_Mode hardware_acceleration_mode { get; set; }
	public string hardware_acceleration_mode_previous { get; set; }
	public Policy3 policy { get; set; }
	public Media_Galleries media_galleries { get; set; }
	public Apps apps { get; set; }
	public Proxy proxy { get; set; }
	public Signin signin { get; set; }
	public Cryptauth cryptauth { get; set; }
	public Recovery_Component recovery_component { get; set; }
	public string allow_dinosaur_easter_egg { get; set; }
	public string dse_geolocation_setting { get; set; }
	public string dse_permissions_settings { get; set; }
	public string dse_was_disabled_by_policy { get; set; }
	public Tab_Stats tab_stats { get; set; }
	public string unsafely_treat_insecure_origin_as_secure { get; set; }
	public Site_Isolation site_isolation { get; set; }
	public File_System file_system { get; set; }
	public Persistent_Notifications persistent_notifications { get; set; }
	public string tab_freezing_enabled { get; set; }
	public Enterprise_Hardware_Platform_Api enterprise_hardware_platform_api { get; set; }
	public Web_Package web_package { get; set; }
	public Hats hats { get; set; }
	public External_Protocol_Dialog external_protocol_dialog { get; set; }
	public string scroll_to_text_fragment_enabled { get; set; }
	public string prompt_on_multiple_matching_certificates { get; set; }
	public string cart_module_hidden { get; set; }
	public string cart_module_welcome_surface_shown_times { get; set; }
	public string cart_discount_acknowledged { get; set; }
	public string cart_discount_enabled { get; set; }
	public string cart_used_discounts { get; set; }
	public string cart_discount_last_fetched_time { get; set; }
	public string cart_discount_consent_shown { get; set; }
	public string discount_consent_decision_made_in { get; set; }
	public string discount_consent_dismissed_in { get; set; }
	public string discount_consent_last_dimissed_time { get; set; }
	public string discount_consent_last_shown_in { get; set; }
	public string discount_consent_dismissed_count { get; set; }
	public string discount_consent_show_interest { get; set; }
	public string discount_consent_show_interest_in { get; set; }
	public string fetch_keepalive_duration_on_shutdown { get; set; }
	public Sharing_Hub sharing_hub { get; set; }
	public Lens lens { get; set; }
	public Privacy_Guide privacy_guide { get; set; }
	public string cors_non_wildcard_request_headers_support { get; set; }
	public string origin_agent_cluster_default_enabled { get; set; }
	public Sct_Auditing sct_auditing { get; set; }
	public High_Efficiency high_efficiency { get; set; }
	public Performance_Intervention performance_intervention { get; set; }
	public string should_show_price_track_fue_bubble_fue { get; set; }
	public string strict_mime_type_check_for_worker_scripts_enabled { get; set; }
	public string access_control_allow_methods_in_cors_preflight_spec_conformant { get; set; }
	public Https_Upgrades https_upgrades { get; set; }
	public Certificates certificates { get; set; }
	public Temporary_Setting temporary_setting { get; set; }
	public Enterprise_Logo enterprise_logo { get; set; }
	public Enterprise_Label enterprise_label { get; set; }
	public Enterprise enterprise { get; set; }
	public string web_audio_output_buffering_enabled { get; set; }
}

public class Download_Bubble {
	public string partial_view_enabled { get; set; }
	public string partial_view_impressions { get; set; }
}

public class Profile {
	public string ephemeral_mode { get; set; }
	public string creation_time { get; set; }
	public string icon_version { get; set; }
	public string exit_type { get; set; }
	public string avatar_index { get; set; }
	public string name { get; set; }
	public string using_default_name { get; set; }
	public string using_default_avatar { get; set; }
	public string using_gaia_avatar { get; set; }
	public string managed_users { get; set; }
	public Managed_Accounts managed_accounts { get; set; }
	public Enterprise_Profile_Creation enterprise_profile_creation { get; set; }
	public Content_Settings content_settings { get; set; }
	public string last_used { get; set; }
	public string last_active_profiles { get; set; }
	public string profiles_created { get; set; }
	public string created_by_version { get; set; }
	public string info_cache { get; set; }
	public string profiles_order { get; set; }
	public Web_App web_app { get; set; }
	public Managed_Configuration managed_configuration { get; set; }
	public Default_Content_Setting_Values default_content_setting_values { get; set; }
	public Extensions extensions { get; set; }
	public string browser_guest_enabled { get; set; }
	public string browser_guest_enforced { get; set; }
	public string add_person_enabled { get; set; }
	public string force_browser_signin { get; set; }
	public string picker_availability_on_startup { get; set; }
	public string picker_shown { get; set; }
	public string show_picker_on_startup { get; set; }
	public Web_Share web_share { get; set; }
	public string shared_array_buffer_unrestricted_access_allowed { get; set; }
	public string sandbox_external_protocol_blocked { get; set; }
}

public class Managed_Accounts {
	public Restriction restriction { get; set; }
}

public class Restriction {
	public string value { get; set; }
	public string all_managed_accounts { get; set; }
}

public class Enterprise_Profile_Creation {
	public string keep_existing_data_by_default { get; set; }
}

public class Content_Settings {
	public Had_Three_Consecutive_Denies had_three_consecutive_denies { get; set; }
	public Quiet_Permission_Ui_Promo quiet_permission_ui_promo { get; set; }
	public string data_url_in_svg_use_enabled { get; set; }
}

public class Had_Three_Consecutive_Denies {
	public string notifications { get; set; }
}

public class Quiet_Permission_Ui_Promo {
	public Should_Show should_show { get; set; }
	public Was_Shown was_shown { get; set; }
}

public class Should_Show {
	public string _ { get; set; }
}

public class Was_Shown {
	public string _ { get; set; }
}

public class Web_App {
	public Install install { get; set; }
	public string policy_settings { get; set; }
}

public class Install {
	public string forcelist { get; set; }
}

public class Managed_Configuration {
	public string list { get; set; }
	public string last_hash { get; set; }
}

public class Default_Content_Setting_Values {
	public string protected_media_identifier { get; set; }
}

public class Extensions {
	public Activity_Log activity_log { get; set; }
}

public class Activity_Log {
	public string num_consumers_active { get; set; }
}

public class Web_Share {
	public string visited_targets { get; set; }
}

public class Session {
	public string restore_on_startup { get; set; }
	public string startup_urls { get; set; }
}

public class Intl {
	public string charset_default { get; set; }
}

public class Webkit {
	public Webprefs webprefs { get; set; }
}

public class Webprefs {
	public Fonts fonts { get; set; }
	public string web_security_enabled { get; set; }
	public string dom_paste_enabled { get; set; }
	public string text_areas_are_resizable { get; set; }
	public string javascript_can_access_clipboard { get; set; }
	public string tabs_to_links { get; set; }
	public string allow_running_insecure_content { get; set; }
	public string force_dark_mode_enabled { get; set; }
	public string default_font_size { get; set; }
	public string default_fixed_font_size { get; set; }
	public string minimum_font_size { get; set; }
	public string minimum_logical_font_size { get; set; }
	public string javascript_enabled { get; set; }
	public string loads_images_automatically { get; set; }
	public string plugins_enabled { get; set; }
	public string encrypted_media_enabled { get; set; }
}

public class Fonts {
	public Standard standard { get; set; }
	public Serif serif { get; set; }
	public Sansserif sansserif { get; set; }
	public Fixed _fixed { get; set; }
	public Cursive cursive { get; set; }
	public Fantasy fantasy { get; set; }
	public Math math { get; set; }
}

public class Standard {
	public string Arab { get; set; }
	public string Jpan { get; set; }
	public string Hang { get; set; }
	public string Hans { get; set; }
	public string Hant { get; set; }
	public string Zyyy { get; set; }
}

public class Serif {
	public string Arab { get; set; }
	public string Jpan { get; set; }
	public string Hang { get; set; }
	public string Hans { get; set; }
	public string Hant { get; set; }
	public string Zyyy { get; set; }
}

public class Sansserif {
	public string Arab { get; set; }
	public string Jpan { get; set; }
	public string Hang { get; set; }
	public string Hans { get; set; }
	public string Hant { get; set; }
	public string Zyyy { get; set; }
}

public class Fixed {
	public string Jpan { get; set; }
	public string Hang { get; set; }
	public string Hans { get; set; }
	public string Hant { get; set; }
	public string Zyyy { get; set; }
}

public class Cursive {
	public string Zyyy { get; set; }
}

public class Fantasy {
	public string Zyyy { get; set; }
}

public class Math {
	public string Zyyy { get; set; }
}

public class Ssl {
	public string error_override_allowed { get; set; }
	public string error_override_allowed_for_origins { get; set; }
	public Rev_Checking rev_checking { get; set; }
	public string version_min { get; set; }
	public string version_max { get; set; }
	public Cipher_Suites cipher_suites { get; set; }
	public Client_Certs client_certs { get; set; }
	public string post_quantum_enabled { get; set; }
	public string ech_enabled { get; set; }
}

public class Rev_Checking {
	public string enabled { get; set; }
	public string required_for_local_anchors { get; set; }
}

public class Cipher_Suites {
	public string blacklist { get; set; }
}

public class Client_Certs {
	public string h2_coalescing_hosts { get; set; }
}

public class Search {
	public string suggest_enabled { get; set; }
}

public class Download {
	public string prompt_for_download { get; set; }
	public string default_directory { get; set; }
	public string directory_upgrade { get; set; }
	public string extensions_to_open { get; set; }
	public string extensions_to_open_by_policy { get; set; }
	public string allowed_urls_for_open_by_policy { get; set; }
}

public class Net {
	public string quic_allowed { get; set; }
	public string keep_whitespace_data_urls { get; set; }
	public string network_qualities { get; set; }
	public string easter_egg_high_score { get; set; }
	public string network_prediction_options { get; set; }
	public string max_connections_per_proxy { get; set; }
	public string explicitly_allowed_network_ports { get; set; }
	public string compression_dictionary_transport_enabled { get; set; }
	public string zstd_content_encoding_enabled { get; set; }
	public string ipv6_reachability_override_enabled { get; set; }
}

public class Browser {
	public string show_home_button { get; set; }
	public string show_forward_button { get; set; }
	public Theme theme { get; set; }
	public string default_browser_infobar_last_declined { get; set; }
	public string default_browser_infobar_last_declined_time { get; set; }
	public string default_browser_infobar_declined_count { get; set; }
	public string default_browser_app_menu_first_shown_time { get; set; }
	public string default_browser_setting_enabled { get; set; }
	public string has_seen_welcome_page { get; set; }
	public string suppress_default_browser_prompt_for_version { get; set; }
	public string default_browser_prompt_refresh_study_group { get; set; }
	public string window_placement { get; set; }
	public string window_placement_popup { get; set; }
	public string app_window_placement { get; set; }
	public string last_redirect_origin { get; set; }
	public string dns_interception_checks_enabled { get; set; }
	public string command_line_flag_security_warnings_enabled { get; set; }
	public string promotions_enabled { get; set; }
	public string suppress_unsupported_os_warning { get; set; }
	public Web_App1 web_app { get; set; }
	public string disk_cache_dir { get; set; }
	public string disk_cache_size { get; set; }
	public string relaunch_notification { get; set; }
	public string relaunch_notification_period { get; set; }
	public string relaunch_window { get; set; }
	public string attempted_to_enable_autoupdate { get; set; }
	public string last_whats_new_version { get; set; }
	public Hovercard hovercard { get; set; }
}

public class Theme {
	public string saved_local_theme { get; set; }
	public string color_scheme { get; set; }
	public string color_scheme2 { get; set; }
	public string user_color { get; set; }
	public string user_color2 { get; set; }
	public string color_variant { get; set; }
	public string color_variant2 { get; set; }
	public string follows_system_colors { get; set; }
	public string is_grayscale { get; set; }
	public string is_grayscale2 { get; set; }
}

public class Web_App1 {
	public string create_on_desktop { get; set; }
	public string create_in_apps_menu { get; set; }
	public string create_in_quick_launch_bar { get; set; }
}

public class Hovercard {
	public string image_previews_enabled { get; set; }
	public string memory_usage_enabled { get; set; }
}

public class Settings {
	public string allowed_domains_for_apps { get; set; }
	public A11y a11y { get; set; }
}

public class A11y {
	public string enable_accessibility_image_labels { get; set; }
	public string enable_accessibility_image_labels_opt_in_accepted { get; set; }
	public string focus_highlight { get; set; }
	public string enable_main_node_annotations { get; set; }
	public string page_colors { get; set; }
	public string apply_page_colors_only_on_increased_contrast { get; set; }
	public string page_colors_block_list { get; set; }
	public string prefers_default_scrollbar_styles { get; set; }
	public Caretbrowsing caretbrowsing { get; set; }
}

public class Caretbrowsing {
	public string enabled { get; set; }
	public string show_dialog { get; set; }
}

public class Extensions1 {
	public Theme1 theme { get; set; }
	public Ui ui { get; set; } = new();
	public string commands { get; set; }
	public string disabled { get; set; }
}

public class Theme1 {
	public string pack { get; set; }
	public string id { get; set; }
}

public class Ui {
	public bool developer_mode { get; set; } = true;
}

public class Autogenerated {
	public Theme2 theme { get; set; }
}

public class Theme2 {
	public string color { get; set; }
	public ChromePolicy policy { get; set; }
}

public class ChromePolicy {
	public string color { get; set; }
}

public class Plugins {
	public string always_open_pdf_externally { get; set; }
}

public class Accessibility {
	public string shown_api_type { get; set; }
}

public class Partition {
	public string default_zoom_level { get; set; }
	public string per_host_zoom_levels { get; set; }
}

public class Media {
	public string prefixed_fullscreen_video_api_availability { get; set; }
	public string default_audio_capture_device { get; set; }
	public string default_video_capture_Device { get; set; }
	public string storage_id_salt { get; set; }
	public Engagement engagement { get; set; }
	public string autoplay_allowed { get; set; }
	public string autoplay_whitelist { get; set; }
	public string block_autoplay { get; set; }
}

public class Engagement {
	public string schema_version { get; set; }
}

public class Printing {
	public string printer_type_deny_list { get; set; }
	public string print_header_footer { get; set; }
	public string allowed_background_graphics_modes { get; set; }
	public string background_graphics_default { get; set; }
	public string paper_size_default { get; set; }
	public string print_preview_disabled { get; set; }
	public string default_destination_selection_rules { get; set; }
	public string use_system_default_printer { get; set; }
	public string print_preview_sticky_settings { get; set; }
}

public class Downgrade {
	public string snapshot_retention_limit { get; set; }
}

public class Message_Center {
	public string disabled_extension_ids { get; set; }
}

public class Fullscreen {
	public string allowed { get; set; }
}

public class Gcm {
	public string push_messaging_application_id_map { get; set; }
	public string product_category_for_subtypes { get; set; }
}

public class Easy_Unlock {
	public string allowed { get; set; }
	public string pairing { get; set; }
	public string device_id { get; set; }
}

public class Webrtc {
	public string ip_handling_policy { get; set; }
	public string udp_port_range { get; set; }
	public string event_logs_collection { get; set; }
	public string local_ips_allowed_urls { get; set; }
	public string text_log_collection_allowed { get; set; }
}

public class Side_Panel {
	public string is_right_aligned { get; set; }
	public string companion_pinned_to_toolbar { get; set; }
	public string id_to_width { get; set; }
	public string google_search_side_panel_enabled { get; set; }
}

public class Tab_Search {
	public string is_right_aligned { get; set; }
}

public class Enterprise_Reporting {
	public string reporting_endpoints { get; set; }
}

public class Managed {
	public string serial_allow_all_ports_for_urls { get; set; }
	public string serial_allow_usb_devices_for_urls { get; set; }
	public string web_hid_allow_all_devices_for_urls { get; set; }
	public string web_hid_allow_devices_for_urls { get; set; }
	public string web_hid_allow_devices_for_urls_on_login_screen { get; set; }
	public string web_hid_allow_devices_with_hid_usages_for_urls { get; set; }
}

public class Profiles {
	public string profiles_deleted { get; set; }
}

public class User_Experience_Metrics {
	public Stability stability { get; set; }
}

public class Stability {
	public string other_user_crash_count { get; set; }
	public string kernel_crash_count { get; set; }
	public string system_unclean_shutdowns { get; set; }
}

public class Task_Manager {
	public string window_placement { get; set; }
	public string column_visibility { get; set; }
	public string end_process_enabled { get; set; }
}

public class Savefile {
	public string default_directory { get; set; }
	public string type { get; set; }
}

public class Selectfile {
	public string last_directory { get; set; }
}

public class Select_File_Dialogs {
	public string allowed { get; set; }
}

public class Filebrowser {
	public Tasks tasks { get; set; }
}

public class Tasks {
	public string default_by_mime_type { get; set; }
	public string default_by_suffix { get; set; }
}

public class Protocol_Handler {
	public string allowed_origin_protocol_pairs { get; set; }
	public Policy1 policy { get; set; }
}

public class Policy1 {
	public string auto_launch_protocols_from_origins { get; set; }
}

public class Restart {
	public Last last { get; set; }
}

public class Last {
	public Session1 session { get; set; }
}

public class Session1 {
	public On on { get; set; }
}

public class On {
	public string shutdown { get; set; }
}

public class Was {
	public string restarted { get; set; }
}

public class Ntp {
	public string collapsed_foreign_sessions { get; set; }
	public string custom_background_dict { get; set; }
	public string custom_background_dict2 { get; set; }
	public string custom_background_local_to_device { get; set; }
	public string custom_background_local_to_device_id { get; set; }
	public string custom_background_inspiration { get; set; }
	public string promo_blocklist { get; set; }
	public string promo_visible { get; set; }
	public string wallpaper_search_history { get; set; }
}

public class Newtabpage {
	public string CustomizeChromeButtonOpenCount { get; set; }
	public string DisabledModules { get; set; }
	public string ModulesOrder { get; set; }
	public string ModulesVisible { get; set; }
	public string ModulesLoadedCountDict { get; set; }
	public string ModulesInteractedCountDict { get; set; }
	public string OutlookModuleVisible { get; set; }
	public string SharepointModuleVisible { get; set; }
	public string WallpaperSearchButtonShownCount { get; set; }
}

public class Colorpicker {
	public string SeedColorChangeCount { get; set; }
}

public class Devtools {
	public string adb_key { get; set; }
	public string availability { get; set; }
	public string last_open_timestamp { get; set; }
	public Remote_Debugging remote_debugging { get; set; }
	public string backgroundserviceexpiration { get; set; }
	public string discover_usb_devices { get; set; }
	public string edited_files { get; set; }
	public string file_system_paths { get; set; }
	public string port_forwarding_enabled { get; set; }
	public string port_forwarding_default_set { get; set; }
	public string port_forwarding_config { get; set; }
	public string discover_tcp_targets { get; set; }
	public string tcp_discovery_config { get; set; }
	public string preferences { get; set; }
	public string sync_preferences { get; set; }
	public string synced_preferences_sync_enabled { get; set; }
	public string synced_preferences_sync_disabled { get; set; }
	public string gen_ai_settings { get; set; }
}

public class Remote_Debugging {
	public string allowed { get; set; }
}

public class Sync_Promo {
	public string user_menu_show_count { get; set; }
}

public class Web_App2 {
	public App_Id app_id { get; set; }
}

public class App_Id {
	public string install_url { get; set; }
}

public class Web_Apps {
	public string daily_metrics { get; set; }
	public string daily_metrics_date { get; set; }
	public string app_agnostic_iph_state { get; set; }
	public string app_agnostic_ml_state { get; set; }
	public string app_agnostic_iph_link_capturing_state { get; set; }
	public string last_preinstall_synchronize_version { get; set; }
	public string did_migrate_default_chrome_apps { get; set; }
	public string uninstalled_default_chrome_apps { get; set; }
	public string web_app_ids { get; set; }
}

public class Background_Contents {
	public string registered { get; set; }
}

public class Auth {
	public string schemes { get; set; }
	public string http_auth_allowed_for_origins { get; set; }
	public string disable_negotiate_cname_lookup { get; set; }
	public string enable_negotiate_port { get; set; }
	public string server_allowlist { get; set; }
	public string negotiate_delegate_whitelist { get; set; }
	public string gssapi_library_name { get; set; }
	public string android_negotiate_account_type { get; set; }
	public string allow_cross_origin_prompt { get; set; }
	public string globally_scoped_http_auth_cache_enabled { get; set; }
	public string ambient_auth_in_private_modes { get; set; }
	public string basic_over_http_enabled { get; set; }
}

public class Hsts {
	public Policy2 policy { get; set; }
}

public class Policy2 {
	public string upgrade_bypass_list { get; set; }
}

public class Async_Dns {
	public string enabled { get; set; }
	public string additional_dns_query_types_enabled { get; set; }
}

public class Dns_Over_Https {
	public string mode { get; set; }
	public string templates { get; set; }
}

public class Hardware {
	public string audio_capture_enabled { get; set; }
	public string audio_capture_allowed_urls { get; set; }
	public string video_capture_enabled { get; set; }
	public string video_capture_allowed_urls { get; set; }
	public string screen_capture_enabled { get; set; }
	public string screen_capture_allowed_by_origins { get; set; }
	public string window_capture_allowed_by_origins { get; set; }
	public string tab_capture_allowed_by_origins { get; set; }
	public string same_origin_tab_capture_allowed_by_origins { get; set; }
}

public class Feedback {
	public string performance_tracing_enabled { get; set; }
}

public class Media_Router {
	public string enable_media_router { get; set; }
	public string show_cast_icon_in_toolbar { get; set; }
}

public class Cloud_Print {
	public string _0 { get; set; }
	public string enabled { get; set; }
	public string proxy_id { get; set; }
	public string auth_token { get; set; }
	public string email { get; set; }
	public string print_system_settings { get; set; }
	public string enable_job_poll { get; set; }
	public string robot_refresh_token { get; set; }
	public string robot_email { get; set; }
	public User_Settings user_settings { get; set; }
	public string xmpp_ping_enabled { get; set; }
	public string xmpp_ping_timeout_sec { get; set; }
}

public class User_Settings {
	public string connectNewPrinters { get; set; }
	public string _0 { get; set; }
	public string printers { get; set; }
}

public class Background_Mode {
	public string enabled { get; set; }
}

public class Hardware_Acceleration_Mode {
	public string enabled { get; set; }
}

public class Policy3 {
	public string device_refresh_rate { get; set; }
	public string device_attributes_allowed_for_origins { get; set; }
	public string lens_region_search_enabled { get; set; }
	public string lens_desktop_ntp_search_enabled { get; set; }
}

public class Media_Galleries {
	public string gallery_id { get; set; }
	public string remembered_galleries { get; set; }
}

public class Apps {
	public string shortcuts_version { get; set; }
	public string shortcuts_arch { get; set; }
}

public class Proxy {
	public string quick_check_enabled { get; set; }
}

public class Signin {
	public string interception_enabled { get; set; }
}

public class Cryptauth {
	public string instance_id { get; set; }
	public string instance_id_token { get; set; }
}

public class Recovery_Component {
	public string needs_elevation { get; set; }
}

public class Tab_Stats {
	public string total_tab_count_max { get; set; }
	public string max_tabs_per_window { get; set; }
	public string window_count_max { get; set; }
	public string last_daily_sample { get; set; }
	public string discards_external { get; set; }
	public string discards_urgent { get; set; }
	public string discards_proactive { get; set; }
	public string discards_suggested { get; set; }
	public string discards_frozen { get; set; }
	public string reloads_external { get; set; }
	public string reloads_urgent { get; set; }
	public string reloads_proactive { get; set; }
	public string reloads_suggested { get; set; }
	public string reloads_frozen { get; set; }
}

public class Site_Isolation {
	public string isolate_origins { get; set; }
	public string site_per_process { get; set; }
}

public class File_System {
	public string file_or_directory_picker_without_allowed_for_origins { get; set; }
}

public class Persistent_Notifications {
	public string next_id { get; set; }
	public string next_trigger { get; set; }
}

public class Enterprise_Hardware_Platform_Api {
	public string enabled { get; set; }
}

public class Web_Package {
	public Signed_Exchange signed_exchange { get; set; }
}

public class Signed_Exchange {
	public string enabled { get; set; }
}

public class Hats {
	public string survey_metadata { get; set; }
}

public class External_Protocol_Dialog {
	public string show_always_open_checkbox { get; set; }
}

public class Sharing_Hub {
	public string desktop_sharing_hub_enabled { get; set; }
}

public class Lens {
	public string lens_overlay_start_count { get; set; }
}

public class Privacy_Guide {
	public string viewed { get; set; }
}

public class Sct_Auditing {
	public string hashdance_report_count { get; set; }
}

public class High_Efficiency {
	public string chip_expanded_count { get; set; }
	public string last_chip_expanded_timestamp { get; set; }
}

public class Performance_Intervention {
	public string background_cpu_message_count { get; set; }
	public string background_cpu_rate_limited_count { get; set; }
	public string last_daily_sample { get; set; }
}

public class Https_Upgrades {
	public Policy4 policy { get; set; }
}

public class Policy4 {
	public string http_allowlist { get; set; }
	public string upgrades_enabled { get; set; }
}

public class Certificates {
	public string ca_certificates { get; set; }
	public string ca_certificates_with_constraints { get; set; }
	public string ca_distrusted_certificates { get; set; }
	public string ca_hint_certificates { get; set; }
	public string ca_platform_integration_enabled { get; set; }
}

public class Temporary_Setting {
	public string enterpise_badging { get; set; }
}

public class Enterprise_Logo {
	public Url url { get; set; }
}

public class Url {
	public string _0 { get; set; }
	public string for_profile { get; set; }
}

public class Enterprise_Label {
	public Custom_Value custom_value { get; set; }
}

public class Custom_Value {
	public string _0 { get; set; }
	public string for_profile { get; set; }
}

public class Enterprise {
	public Profile_Badging profile_badging { get; set; }
}

public class Profile_Badging {
	public string toolbar_settings { get; set; }
}

