<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="addons\**" />
		<EmbeddedResource Include="json\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="addons\foxameleon_proxy\background.js" />
	  <None Remove="addons\foxameleon_proxy\manifest.json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
	</ItemGroup>

</Project>
