<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="addons\**" />
		<EmbeddedResource Include="json\**" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="addons\chromeleon\modules\uule.js" />
	  <None Remove="addons\extreloader\background.js" />
	  <None Remove="addons\extreloader\manifest.json" />
	  <None Remove="addons\foxameleon\modules\uule.js" />
	  <None Remove="addons\foxameleon\scripts\content-script.js" />
	  <None Remove="addons\foxyproxy\background.js" />
	  <None Remove="addons\foxyproxy\manifest.json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Chameleon.lib.Common\Chameleon.lib.Common.csproj" />
	</ItemGroup>

</Project>
